# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Disable dnf module postgresql
  ansible.builtin.command: dnf module disable postgresql -y
  when: ansible_distribution_major_version | int > 7
  register: dnf_result
  changed_when: '"Disabling modules" in dnf_result.stdout'
  notify: yum makecache

- ansible.builtin.import_tasks: public_repo.yml

- name: Install PostgreSQL adapter for python
  ansible.builtin.yum:
    name: "{{ postgresql_client_default_packages[packages_version] }}"
    state: present
  vars:
    packages_version: "{{ ( (ansible_distribution_major_version | int) < 8) | ternary('legacy','modern') }}"
