# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Disable dnf module postgresql
  command: dnf module disable postgresql -y
  args:
    warn: no
  when: ansible_distribution_major_version | int > 7
  register: dnf_result
  changed_when: '"Disabling modules" in dnf_result.stdout'
  notify: yum makecache

- import_tasks: public_repo.yml

- name: Install PostgreSQL packages
  yum:
    name: "{{ postgresql_default_packages['common'] + postgresql_default_packages[packages_version] }}"
    state: present
  vars:
    packages_version: "{{ ( (ansible_distribution_major_version | int) < 8) | ternary('legacy','modern') }}"
