# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---

- name: Install from public repo
  block:
    - name: Disable dnf module postgresql
      command: dnf module disable postgresql -y
      args:
        warn: no
      when: ansible_distribution_major_version | int > 7
      register: dnf_result
      changed_when: '"Disabling modules" in dnf_result.stdout'
      notify: yum makecache

    - import_tasks: public_repo.yml

    - name: Install PostgreSQL packages
      yum:
        name: "{{ postgresql_default_packages['common'] + postgresql_default_packages[packages_version] }}"
        state: present
      vars:
        packages_version: "{{ ( (ansible_distribution_major_version | int) < 8) | ternary('legacy','modern') }}"
  when: postgresql_airgap_install == false

- name: Install from provided packages
  block:

    - name: Disable dnf module postgresql
      command: dnf module disable postgresql -y
      args:
        warn: no
      when: ansible_distribution_major_version | int > 7
      register: dnf_result
      changed_when: '"Disabling modules" in dnf_result.stdout'
      notify: yum makecache

    - name: Upload {{ item }}
      copy:
        src: files/{{ item }}
        dest: "{{ binaries_upload_dir }}"
        owner: root
        group: root
        mode: "644"
      diff: false
      vars:
        packages_version: "{{ ( (ansible_distribution_major_version | int) < 8) | ternary('legacy','modern') }}"
      loop: "{{ postgresql_default_packages['common'] + postgresql_default_packages[packages_version] }}"
      when: postgresql_install_from_file == true

    - name: Install PostgreSQL packages
      yum:
        name: "{{ postgresql_default_packages_path['common'] + postgresql_default_packages_path[packages_version] }}"
        state: present
      vars:
        packages_version: "{{ ( (ansible_distribution_major_version | int) < 8) | ternary('legacy','modern') }}"

  when: postgresql_airgap_install == true
