# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Restart PostgreSQL server
  ansible.builtin.service:
    name: postgresql-{{ postgresql_version }}
    state: restarted
    enabled: true
