# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Stop PostgreSQL server
  ansible.builtin.service:
    name: postgresql-{{ postgresql_version }}
    state: stopped
    enabled: true
