# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Start and enable cgconfig service
  ansible.builtin.service:
    name: cgconfig
    state: started
    enabled: yes

- name: Start and enable cgred service
  ansible.builtin.service:
    name: cgred
    state: started
    enabled: yes
  when: ansible_distribution_major_version | int < 8
