# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Check if firewalld is installed
  ansible.builtin.yum:
    list: installed
  register: yum_installed

- name: Stop and disable firewalld
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: no
  when: "'firewalld' in (yum_installed.results | map(attribute='name'))"
