# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
# Adapted from https://github.com/kubernetes-sigs/kubespray/blob/v2.16.0/roles/bootstrap-os/tasks/bootstrap-centos.yml
- name: Add proxy to yum.conf or dnf.conf if http_proxy is defined
  community.general.ini_file:
    path: "{{ ( (ansible_distribution_major_version | int) < 8) | ternary('/etc/yum.conf','/etc/dnf/dnf.conf') }}"
    section: main
    option: proxy
    value: "{{ http_proxy | default(omit) }}"
    state: "{{ http_proxy | default(False) | ternary('present', 'absent') }}"
    no_extra_spaces: true

- name: Install common packages
  ansible.builtin.yum:
    name: "{{ default_packages['common'] + default_packages[packages_version] }}"
    state: present
  vars:
    packages_version: "{{ ( (ansible_distribution_major_version | int) < 8) | ternary('legacy','modern') }}"
