# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Upgrade pip3
  ansible.builtin.pip:
    name:
      - pip
    state: latest
    executable: pip3
  environment: "{{ proxy_env }}"

- name: Install numpy, pandas and pyarrow
  ansible.builtin.pip:
    name:
      - numpy~=1.19
      - pandas~=1.0
      - pyarrow~=4.0
      - py4j~=0.10.9
    state: latest
    executable: pip3
  environment: "{{ proxy_env }}"

# https://developers.redhat.com/blog/2019/05/07/what-no-python-in-red-hat-enterprise-linux-8
- name: Set alternatives for Rocky8
  community.general.alternatives:
    name: python
    path: /usr/bin/python3
  when: ansible_distribution_major_version | int > 7
