# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Ensure powertools repository is enabled
  community.general.ini_file:
    path: "{{ repos[ansible_distribution_major_version]['path'] }}"
    section: "{{ repos[ansible_distribution_major_version]['section'] }}"
    option: enabled
    value: "1"
    no_extra_spaces: yes
  vars:
    repos:
      '8':
        path: /etc/yum.repos.d/Rocky-PowerTools.repo
        section: powertools
  when: "(ansible_distribution_major_version | int) >= 8"

- name: Install R
  ansible.builtin.yum:
    name: R
    state: present
