# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Ensure certificates storing folder exists
  ansible.builtin.file:
    path: "{{ certificates_path }}/{{ certificates_cluster_name }}_certs"
    state: directory

- name: Send host's CSR to CA machine
  ansible.builtin.copy:
    src: "{{ certificates_local_path }}/{{ certificates_cluster_name }}_certs/{{ certificates_cert_filename }}.csr"
    dest: "{{ certificates_path }}/{{ certificates_cluster_name }}_certs/"

- name: Generate {{ certificates_cert_filename }} certificate
  community.crypto.x509_certificate:
    provider: ownca
    path: "{{ certificates_path }}/{{ certificates_cluster_name }}_certs/{{ certificates_cert_filename }}.pem"
    csr_path: "{{ certificates_path }}/{{ certificates_cluster_name }}_certs/{{ certificates_cert_filename }}.csr"
    ownca_path: "{{ certificates_path }}/{{ certificates_ca_filename }}.crt"
    ownca_privatekey_path: "{{ certificates_path }}/{{ certificates_ca_filename }}.key"

- name: Fetch host's signed certificate
  ansible.builtin.fetch:
    src: "{{ certificates_path }}/{{ certificates_cluster_name }}_certs/{{ certificates_cert_filename }}.pem"
    dest: "{{ certificates_local_path }}/{{ certificates_cluster_name }}_certs/"
    flat: yes
