# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Install chrony 
  ansible.builtin.package:
    name: chrony 
    
- name: Configure chrony
  ansible.builtin.template:
    dest: /etc/chrony.conf
    src: chrony.conf.j2
  notify: restart chronyd

- name: Start and enable chronyd service
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: yes
