# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
proxy_env:
  http_proxy: "{{ http_proxy | default ('') }}"
  HTTP_PROXY: "{{ http_proxy | default ('') }}"
  https_proxy: "{{ https_proxy | default ('') }}"
  HTTPS_PROXY: "{{ https_proxy | default ('') }}"
  no_proxy: "{{ no_proxy | default ('') }}"
  NO_PROXY: "{{ no_proxy | default ('') }}"

default_packages:
  common:
    - tar
    - vim
    - java-1.8.0-openjdk
    - wget
    - curl
    - unzip
    - nmap-ncat
    - expect
    - python3
    - python3-pip
    - python3-setuptools
    - python3-virtualenv
    - python3-lxml
    - R
    - libcgroup-tools
  legacy: # centos 7 and below
    # Installing python2-setuptools required by the Ansible pip module
    - authconfig
    - python2-setuptools
    - python2-cryptography
    - python2-virtualenv
  modern: # centos 8 and above
    - authselect
    - python2
    - python3-cryptography
