# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- hosts: all
  tasks:
    - ansible.builtin.import_role:
        name: tosit.tdp_prerequisites.chrony
      when: not (ansible_virtualization_role == 'guest' and ansible_virtualization_type == 'lxc')
