# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Start krb5kdc/kadmin server
  hosts: kdc
  tasks:
    - name: Start krb5kdc/kadmin server
      ansible.builtin.import_role:
        name: tosit.tdp_prerequisites.ldap_kerberos
        tasks_from: start_kerberos.yml
