# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Stop kadmin/krb5kdc server
  hosts: kdc
  tasks:
    - name: Stop kadmin/krb5kdc server
      ansible.builtin.import_role:
        name: tosit.tdp_prerequisites.ldap_kerberos
        tasks_from: stop_kerberos.yml
