# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- hosts: kdc
  tasks:
    - ansible.builtin.import_role:
        name: tosit.tdp_prerequisites.ldap_kerberos

- hosts: kdcproxy
  tasks:
    - ansible.builtin.import_role:
        name: tosit.tdp_prerequisites.ldap_kerberos
        tasks_from: install_kdcproxy.yml

- hosts: all
  tasks:
    - ansible.builtin.import_role:
        name: tosit.tdp_prerequisites.ldap_kerberos
        tasks_from: sssd.yml
    - ansible.builtin.import_role:
        name: tosit.tdp_prerequisites.ldap_kerberos
        tasks_from: install_kerberos_client.yml

- hosts: users_keytab
  tasks:
    - ansible.builtin.import_role:
        name: tosit.tdp_prerequisites.ldap_kerberos
        tasks_from: create_users_keytab.yml
