# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Start OpenLDAP server
  hosts: kdc
  tasks:
    - name: Start OpenLDAP server
      ansible.builtin.import_role:
        name: tosit.tdp_prerequisites.ldap_kerberos
        tasks_from: start_openldap.yml
