# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Restart OpenLDAP server
  hosts: kdc
  tasks:
    - name: Restart OpenLDAP server
      ansible.builtin.import_role:
        name: tosit.tdp_prerequisites.ldap_kerberos
        tasks_from: restart_openldap.yml
