# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Stop PostgreSQL server
  hosts: postgresql
  tasks:
    - name: Stop PostgreSQL server
      ansible.builtin.import_role:
        name: tosit.tdp_prerequisites.postgresql
        tasks_from: stop.yml
