# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- hosts: postgresql
  tasks:
    - ansible.builtin.import_role:
        name: tosit.tdp_prerequisites.postgresql

- hosts: postgresql_client
  tasks:
    - ansible.builtin.import_role:
        name: tosit.tdp_prerequisites.postgresql
        tasks_from: packages_client.yml
