# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Stop sssd server
  hosts: all
  tasks:
    - name: Stop sssd server
      ansible.builtin.import_role:
        name: tosit.tdp_prerequisites.ldap_kerberos
        tasks_from: stop_sssd.yml
