# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: yum makecache
  ansible.builtin.command: yum makecache -y

- name: restart postgresql
  ansible.builtin.service:
    name: "{{ postgresql_service }}"
    state: restarted

- name: reload postgresql
  ansible.builtin.service:
    name: "{{ postgresql_service }}"
    state: reloaded
