# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: yum makecache
  command: yum makecache -y
  args:
    warn: False

- name: restart postgresql
  service:
    name: "{{ postgresql_service }}"
    state: restarted

- name: reload postgresql
  service:
    name: "{{ postgresql_service }}"
    state: reloaded
