# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Install Kerberos client package
  ansible.builtin.package:
    name: krb5-workstation

- name: Add krb5.conf
  ansible.builtin.template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf

- name: Add krb5-https.conf
  ansible.builtin.template:
    src: krb5.conf.j2
    dest: /etc/krb5-https.conf
  when: "'kdcproxy' in groups"
  vars:
    kerberos_servers: "{{ kdcproxy_servers }}"
