# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Install packages
  ansible.builtin.package:
    name:
      - openldap-servers
      - openldap-clients
      - krb5-workstation
      - krb5-libs
      - krb5-server
      - krb5-server-ldap
