# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Start krb5kdc server
  ansible.builtin.service:
    name: krb5kdc
    state: started
    enabled: true

- name: Start kadmin server
  ansible.builtin.service:
    name: kadmin
    state: started
    enabled: true
